package christian.chamorro.mercadolibresearch.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF313379)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFF0F2FC)
val md_theme_light_onPrimaryContainer = Color(0xFF561E00)
val md_theme_light_secondary = Color(0xFFFFC500)
val md_theme_light_onSecondary = Color(0xFFF3F6F8)
val md_theme_light_secondaryContainer = Color(0xFFF9AA33)
val md_theme_light_onSecondaryContainer = Color(0xFF2A1800)
val md_theme_light_tertiary = Color(0xFF152A57)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE5E8FA)
val md_theme_light_onTertiaryContainer = Color(0xFFC6CCEE)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFF5ACAC)
val md_theme_light_onError = Color(0xFFFAF7F7)
val md_theme_light_onErrorContainer = Color(0xFF770E11)
val md_theme_light_background = Color(0x86FFFFFF)
val md_theme_light_onBackground = Color(0xFF030865)
val md_theme_light_surface = Color(0xFFFFC500)
val md_theme_light_onSurface = Color(0xFF030865)
val md_theme_light_surfaceVariant = Color(0xFFF2F4FC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFF177A1D)
val md_theme_light_inverseSurface = Color(0xFF1E2578)
val md_theme_light_inversePrimary = Color(0xFFD39F52)
val md_theme_light_surfaceTint = Color(0xFF6F98B8)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)
